__test__/components/__snapshots__/activities.test.tsx.snap, __test__/components/__snapshots__/objects-group.test.tsx.snap, __test__/components/__snapshots__/project-structure.test.tsx.snap, __test__/components/activities.test.tsx, __test__/components/objects-group.test.tsx, __test__/components/project-structure.test.tsx, __test__/reducers/activities-reducer.test.ts, __test__/reducers/group-objects-reducer.test.ts, __test__/reducers/project-structure-reducer.test.ts, jest.config.js, package.json, src/components/activities/index.tsx, src/components/geological-exploration/index.tsx, src/components/objects-group/index.tsx, src/components/project-structure/index.tsx, src/utils/create-reducer.ts, yarn.lock
Добавлены тесты на основные компоненты и редьюсеры
=> test(global): добавление тестов для основных компонентов и редьюсеров

src/components/canvas/index.tsx, src/redux-store/activities/actions.ts, src/redux-store/group-objects/actions.ts, src/redux-store/logic-constructor/actions.ts, src/redux-store/project-structure/actions.ts, src/redux-store/version/actions.ts, src/utils/debounce.ts, src/utils/graphql-request.ts, src/utils/headers.ts, src/utils/sync-canvas-request-body.ts
Задача в Jira: https://jira.konakov.tv/browse/VEGA-2493
Ссылка на стенд: https://VEGA-2493.vega-2.csssr.cloud
Фикс не закрывающейся панели редактирования шага при удалении последнего
Рефакторинг запросов
=> Jira issue: VEGA-2493

src/redux-store/activities/actions.ts, src/redux-store/group-objects/actions.ts, src/redux-store/logic-constructor/actions.ts, src/redux-store/project-structure/actions.ts, src/redux-store/version/actions.ts, src/utils/graphql-request.ts
Задача в Jira: https://jira.konakov.tv/browse/VEGA-2650
Фикс увеличивающейся версии при неудачном запросе (с errors)
Jira issue: VEGA-2700
=> VEGA-2650: фикс увеличивающейся версии при неудачном запросе

jest.config.js, src/App/App.tsx, src/App/AppView.tsx, src/App/cn-app.ts, src/components/activities/index.css, src/components/activities/index.tsx, src/components/canvas/index.css, src/components/geological-exploration/index.tsx, src/components/in-progress/cn-in-progress.ts, src/components/in-progress/index.css, src/components/in-progress/index.tsx, src/components/logic-constructor/index.css, src/components/logic-constructor/index.tsx, src/components/objects-group/index.tsx, src/components/project-structure/index.tsx, src/react-context/providers/Providers.tsx, src/redux-store/logic-constructor/actions.ts, src/singleSpaEntry.tsx, src/utils/api-clients/vega-api.ts, src/utils/set-public-path.tsx
Задача в Jira: https://jira.konakov.tv/browse/VEGA-2698
Ссылка на стенд: https://VEGA-2698.vega-2.csssr.cloud
Jira issue: VEGA-2698
=> Vega 2698: Уведомление "Раздел находится в разработке'"

src/App/App.css
Задача в Jira: https://jira.konakov.tv/browse/VEGA-2729
Ссылка на стенд: https://VEGA-2729.vega-2.csssr.cloud
Jira issue: VEGA-2729
=> VEGA-2729 временное решение - до исправление header и layout в vega-ui

src/components/canvas/index.tsx, src/components/logic-constructor/index.tsx, src/redux-store/activities/action-types.ts, src/redux-store/activities/actions.ts, src/redux-store/activities/initial-state.ts, src/redux-store/activities/reducer.ts, src/redux-store/activities/selectors.ts, src/redux-store/group-objects/initial-state.ts, src/redux-store/logic-constructor/actions.ts, src/redux-store/logic-constructor/initial-state.ts, src/redux-store/project-structure/initial-state.ts, src/redux-store/version/initial-state.ts, src/types/redux-store.ts, tsconfig.json, webpack.config.js
Задача в Jira: https://jira.konakov.tv/browse/VEGA-2720
Ссылка на стенд: https://VEGA-2720.vega-2.csssr.cloud
=> Vega 2720 Функционал добавления и замены Мероприятия в Шаге

app-config/index.js, webpack.forShellConfig.js
Задача в Jira: https://jira.konakov.tv/browse/VEGA-719
Ссылка на стенд: https://VEGA-719.vega-2.csssr.cloud
=> VEGA-719: Избавиться от упоминаний стендов в репозиториях

package.json, yarn.lock
Задача в Jira: https://jira.konakov.tv/browse/VEGA-728
Ссылка на стенд: https://VEGA-728.vega-2.csssr.cloud
обновлена версия vega-ui
=> VEGA-728: Избавить от дублирования стилей vega-ui

src/components/step-editor/index.css, src/components/step-editor/index.tsx
Задача в Jira: https://jira.konakov.tv/browse/VEGA-2711
Ссылка на стенд: https://VEGA-2711.vega-2.csssr.cloud
Jira issue: VEGA-2711
=> VEGA-2711: Добавление кнопки закрытия панели редактирования шага

__test__/components/__snapshots__/project-structure.test.tsx.snap, src/components/activities/index.css, src/components/canvas/index.css, src/components/canvas/index.tsx, src/components/logic-constructor/index.css, src/components/logic-constructor/index.tsx, src/components/objects-group/index.css, src/components/project-structure/cn-project-structure.ts, src/components/project-structure/index.css, src/components/project-structure/index.tsx, src/redux-store/logic-constructor/actions.ts, src/utils/api-clients/vega-api.ts, src/utils/graphql-request.ts
Задача в Jira: https://jira.konakov.tv/browse/VEGA-2778
Ссылка на стенд: https://VEGA-2778.vega-2.csssr.cloud
- исправлены принудительные скроллы для tree
- обновлена верстка canvas для последующей правильной работы с window resize
- исправлена верстка canvas - внутри Layout
зависит от https://github.com/gpn-prototypes/vega-ui/pull/397
=> Vega-2778: исправление Canvas resize

src/components/canvas/index.tsx, src/components/logic-constructor/index.tsx, src/redux-store/logic-constructor/actions.ts, src/utils/api-clients/vega-api.ts, src/utils/graphql-request.ts, yarn.lock
Задача в Jira: https://jira.konakov.tv/browse/VEGA-2733
Ссылка на стенд: https://VEGA-2733.vega-2.csssr.cloud
Jira issue: VEGA-2733
=> VEGA-2733: Замена логики добавления элемента на Канвас через DND

public/index.html, src/App/App.css
Задача в Jira: https://jira.konakov.tv/browse/VEGA-2734
Ссылка на стенд: https://VEGA-2734.vega-2.csssr.cloud
Jira issue: [VEGA-2734](https://jira.konakov.tv/browse/VEGA-2734)
Правки по стилям обертки КЛ
=> VEGA-2734: Правки по стилям обертки КЛ

src/redux-store/logic-constructor/actions.ts, src/utils/step-data.ts
Задача в Jira: https://jira.konakov.tv/browse/VEGA-2735
Ссылка на стенд: https://VEGA-2735.vega-2.csssr.cloud
Вмержены изменения из VEGA-2785 VEGA-2763, поскольку от них зависят
Исправлены VEGA-2831 VEGA-2829 (поскольку включает их в себя)
=> VEGA-2735: Исправление загрузки дерева сценария

__test__/components/__snapshots__/activities.test.tsx.snap, src/components/activities/index.css, src/components/activities/index.tsx
Задача в Jira: https://jira.konakov.tv/browse/VEGA-2603
Ссылка на стенд: https://VEGA-2603.vega-2.csssr.cloud
=> VEGA-2603: Добавить кнопку скрыть/показать мероприятия

package.json, yarn.lock
=> chore(components): обновление vega-ui

src/App/AppView.tsx, src/components/in-progress/index.css, src/components/logic-constructor/index.tsx, src/config.public.ts, src/utils/api-clients/vega-api.ts, src/utils/graphql-request.ts
Задача в Jira: https://jira.konakov.tv/browse/VEGA-2832
Ссылка на стенд: https://VEGA-2832.vega-2.csssr.cloud
Jira issue: VEGA-2832
=> VEGA-2832: Изменение позиции лейбла "В разработке"

__test__/components/__snapshots__/activities.test.tsx.snap, __test__/components/activities.test.tsx, __test__/components/objects-group.test.tsx, __test__/components/project-structure.test.tsx, package.json, src/components/activities/index.tsx, src/react-context/providers/Providers.tsx, src/redux-store/activities/action-types.ts, src/redux-store/activities/actions.ts, src/redux-store/activities/initial-state.ts, src/redux-store/activities/reducer.ts, src/redux-store/activities/selectors.ts, src/redux-store/index.ts, src/types/redux-store.ts, yarn.lock
Задача в Jira: https://jira.konakov.tv/browse/VEGA-2887
Ссылка на стенд: https://VEGA-2887.vega-2.csssr.cloud
=> [Alpha] VEGA-2887: Сохранение состояния отображения панели мероприятий

__test__/components/__snapshots__/project-structure.test.tsx.snap, src/components/project-structure/index.css, src/components/project-structure/index.tsx, src/redux-store/project-structure/actions.ts, src/redux-store/version/actions.ts
Задача в Jira: https://jira.konakov.tv/browse/VEGA-2906
Ссылка на стенд: https://VEGA-2906.vega-2.csssr.cloud
Jira issue: VEGA-2906
- добавлено сообщение "Структура проекта отсутствует" когда нет сущностей в проекте, либо структура проекта пуста;
- если в проекте нет сущностей, `query` на их получение не создается и запрос не производится
=> [ALPHA] VEGA-2906: Добавление сообщения "Структура проекта отсутствует"

app-config/index.js, src/components/canvas/index.tsx, src/components/step-editor/CommonInfo.tsx, src/components/step-editor/index.css, src/components/step-editor/index.tsx
Задача в Jira: https://jira.konakov.tv/browse/VEGA-2688
Ссылка на стенд: https://VEGA-2688.vega-2.csssr.cloud
Задал структуру для создания списков Параметров и Рисков
Jira issue: VEGA-2688
=> [VEGA-2688] feat(layout): Приведение редактора шага к новому дизайну

__test__/components/__snapshots__/geological-exploration.test.tsx.snap, __test__/components/geological-exploration.test.tsx, src/components/geological-exploration/index.tsx
Задача в Jira: https://jira.konakov.tv/browse/VEGA-3016
Ссылка на стенд: https://VEGA-3016.vega-2.csssr.cloud
Jira issue: VEGA-3016
=> [VEGA-3016] fix(components): Исправление ошибки 404 при переходе к проекту из моков

__test__/App/App.test.tsx, __test__/App/__snapshots__/App.test.tsx.snap
добавлены тесты для компонента App
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND%20TOOLBOX/job/scenario-tests-on-demand/161/
=> [VEGA-3124] test(components): Покрытие тестами src/App

__test__/components/__snapshots__/notifications.test.tsx.snap, __test__/components/notifications.test.tsx, package.json, src/components/header/index.tsx, yarn.lock
- добавлены тесты для компонента нотификаций
- удален компонент Header, поскольку он нигде не использовался
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND%20TOOLBOX/job/scenario-tests-on-demand/162/
=> [VEGA-3127, 3130] test(notifications): Покрытие тестами компонента нотификаций

__test__/components/__snapshots__/logic-constructor.test.tsx.snap, __test__/components/logic-constructor.test.tsx, package.json, yarn.lock
- добавлены тесты для компонента Конструктор Логики
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND%20TOOLBOX/job/scenario-tests-on-demand/165/
=> [VEGA-3128] test(components): Покрытие тестами компонента Конструктор Логики

package.json, src/components/canvas/index.tsx, src/types/redux-store.ts, yarn.lock
=> chore(deps): Обновление Vega-UI

__test__/components/__snapshots__/project-structure.test.tsx.snap, __test__/components/project-structure.test.tsx, src/components/project-structure/index.tsx
Добавлены тесты для компонента Структура Проекта
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND%20TOOLBOX/job/scenario-tests-on-demand/194/
=> [VEGA-3132] test(components): Покрытие тестами компонента Структура Проекта

__test__/components/step-editor/__snapshots__/common-info.test.tsx.snap, __test__/components/step-editor/__snapshots__/conditions.test.tsx.snap, __test__/components/step-editor/__snapshots__/effects.test.tsx.snap, __test__/components/step-editor/__snapshots__/step-editor.test.tsx.snap, __test__/components/step-editor/common-info.test.tsx, __test__/components/step-editor/conditions.test.tsx, __test__/components/step-editor/effects.test.tsx, __test__/components/step-editor/step-editor.test.tsx, package.json, src/components/no-page-found/index.tsx, src/components/step-editor/CommonInfo.tsx, src/components/step-editor/index.tsx, yarn.lock
- Добавлены тесты для компонентов:
+ StepEditor
+ CommonInfo
+ Conditions
+ Effects
- Удален неиспользуемый компонент NoPageFound
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND%20TOOLBOX/job/scenario-tests-on-demand/195/
=> [VEGA-3129, 3133] test(components): Покрытие тестами компонента Редактор шага и его дочерних компонентов

.prettierignore, __test__/components/objects-group-dialog.test.tsx, __test__/components/objects-group.test.tsx
Задача в Jira: https://jira.konakov.tv/browse/VEGA-3131
Ссылка на стенд: https://VEGA-3131.vega-2.csssr.cloud
Jira issue: VEGA-3131
Добавил тесты для групп объектов и диалога создания групп
_{link}_
_{Screenshot}_
_{Screenshot}_
=> [VEGA-3131] test(components): Покрытие тестами objects-group & dialog

__test__/utils/resize-saver-service.test.ts, package.json, src/components/canvas/index.tsx, src/components/geological-exploration/index.tsx, src/redux-store/logic-constructor/actions.ts, src/utils/graphql-request.ts, src/utils/queries.ts, src/utils/resize-saver-service.ts, yarn.lock
Задача в Jira: https://jira.konakov.tv/browse/VEGA-3285
Ссылка на стенд: https://VEGA-3285.vega-2.csssr.cloud
Jira issue: VEGA-3285
Адаптировал функционал удаления канвас нод к новому API канваса, добавил удаление scenarioStep
- Дополнительно: [VEGA-3284](https://jira.vegaspace.tk/browse/VEGA-3284) - Покрыть тестами ResizeSaverService + фикс инициализации id для ResizeSaverService 
_{link}_
_{Screenshot}_
_{Screenshot}_
=> [VEGA-3285] fix(components): Адаптация КЛ под новый API Канваса

__test__/App/App.test.tsx, src/App/App.tsx, src/react-context/providers/ProjectProvider.tsx, src/react-context/providers/Providers.tsx, src/types/index.ts
Задача в Jira: https://jira.konakov.tv/browse/VEGA-3250
Ссылка на стенд: https://VEGA-3250.vega-2.csssr.cloud
Jira issue: VEGA-3250
- Обвязка предосталвяет сервис currentProject, который отдает projectId
_{link}_
_{Screenshot}_
_{Screenshot}_
=> [VEGA-3250] feat(components): Использование currentProject из обвязки

__test__/actions/activities-actions.test.ts, __test__/components/activities.test.tsx, __test__/reducers/activities-reducer.test.ts, src/redux-store/activities/actions.ts, src/redux-store/activities/reducer.ts, src/redux-store/activities/selectors.ts
Задача в Jira: https://jira.konakov.tv/browse/VEGA-3135
Ссылка на стенд: http://ltumoyakov-vega3135-lanit-vega-builder.code013.org
Jira issue: VEGA-3135
Добавлены тесты для activities reducers, actions и selectors
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND%20TOOLBOX/job/scenario-tests-on-demand/368/
=> [VEGA-3135] test(activities): Покрытие тестами src/redux-store/activities

__test__/actions/objects-groups-actions.test.ts, src/redux-store/group-objects/actions.ts, src/redux-store/group-objects/reducer.ts
Задача в Jira: https://jira.konakov.tv/browse/VEGA-3136
Ссылка на стенд: https://VEGA-3136.vega-2.csssr.cloud
Jira issue: VEGA-3136
Покрытие тестами actions для objects-group
_{link}_
_{Screenshot}_
_{Screenshot}_
=> [VEGA-3136] test(components): Тесты для redux-store/objects-group

__test__/components/canvas.test.tsx
Задача в Jira: https://jira.konakov.tv/browse/VEGA-3126
Ссылка на стенд: http://ltumoyakov-vega3126-lanit-vega-builder.code013.org
Jira issue: VEGA-3126
Добавлены тесты компонента CanvasWidget
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND%20TOOLBOX/job/scenario-tests-on-demand/369/
=> [VEGA-3126] test(canvas): Покрытие тестами src/components/canvas

ci/build.sh
Задача в Jira: https://jira.vegaspace.tk/browse/VEGA-3243
Ссылка на стенд: https://VEGA-3243.vega-2.csssr.cloud
https://git.konakov.tv/vega2/vega-builder-automation/-/merge_requests/61
Изменения для общей сборки
_{link}_
_{Screenshot}_
_{Screenshot}_
_{Screenshot}_
=> [VEGA-3243] ci: Исправление общей сборки на YC

__test__/actions/logic-constructor-actions.test.ts, package.json, src/redux-store/logic-constructor/actions.ts, src/redux-store/project-structure/actions.ts, src/redux-store/version/actions.ts, src/utils/queries.ts, tsconfig.json, yarn.lock
Задача в Jira: https://jira.konakov.tv/browse/VEGA-3416
Ссылка на стенд: https://VEGA-3416.vega-2.csssr.cloud
Jira issue: VEGA-3416
_{link}_
_{Screenshot}_
_{Screenshot}_
=> [VEGA-3416] fix(components):  Фикс ошибок 400 при работе с CANVAS

__test__/components/canvas.test.tsx, src/components/canvas/index.tsx
Задача в Jira: https://jira.konakov.tv/browse/VEGA-3296
Ссылка на стенд: https://VEGA-3296.vega-2.csssr.cloud
_{link}_
_{Screenshot}_
_{Screenshot}_
=> [VEGA-3296] fix(components): Фикс крэша канваса при закрытии меню редактирования шага

__test__/actions/project-structure-actions.test.ts, __test__/reducers/project-structure-reducer.test.ts, src/redux-store/project-structure/actions.ts, src/redux-store/project-structure/reducer.ts
Задача в Jira: https://jira.konakov.tv/browse/VEGA-3138
Ссылка на стенд: https://VEGA-3138.vega-2.csssr.cloud
Jira issue: VEGA-3138
- добавлены тесты для project structure actions
- дополнены тесты для project structure reducer
- поправлены тип принимаемых значений в project structure reducer
_{link}_
_{Screenshot}_
_{Screenshot}_
=> [VEGA-3138] test(project-structure): Покрытие тестами src/redux-store/project-structure

package.json, src/components/project-structure/index.tsx, yarn.lock
Задача в Jira: https://jira.konakov.tv/browse/VEGA-3372
Jira issue: VEGA-3372
Обновление vega-ui до версии 3.1.10
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND%20TOOLBOX/job/scenario-tests-on-demand/558/
=> [VEGA-3372] chore(deps): Обновление vega-ui

src/components/geological-exploration/index.tsx, src/components/logic-constructor/index.css
Задача в Jira: https://jira.konakov.tv/browse/VEGA-3017
Jira issue: VEGA-3017
_{Short Issue Description}_
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND%20TOOLBOX/job/scenario-tests-on-demand/559/
=> [VEGA-3017] fix(components): Исправление верстки в маленьком окне

jest.config.js, package.json, yarn.lock
Added jest-junit dependency and reported option
_{link}_
_{Screenshot}_
_{Screenshot}_
_{Screenshot}_
=> jest-junit reporter added
